### ISSUE TITLE
Please note that

### ISSUE THREAD

**Issue by 34641904** [0x120/BlueKeep-Weaponized#1]
Please note that SatoshiDisc does not provide support for the items purchased through a seller via us. If you have questions regarding your product, please contact the seller directly. We can't refund, change, rollback or cancel the transaction because of blockchain protocol. All sales are final.

**Comment by 0x120** [comment]
@34641904 You leave me a message with your issue and btc address where you want the refund.

**Comment by neurosatan** [comment]
> @34641904 You leave me a message with your issue and btc address where you want the refund.

give me email you.

**Comment by 0x120** [comment]
@neurosatan Feel free to contact me at 0x120@protonmail.com. Rolling out an update next week, people who already bought it contact me and I'll give them a free trial of the updated tool.

**Comment by 34641904** [comment]
faker
